version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: nivaran-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: nivaran

  backend:
    build: ./server
    container_name: nivaran-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/nivaran
      PORT: 5000
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: nivaran-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data:
